# Batch Processing Configuration - UNFINALIZED REFERENCES TEST
# Find and process the next 5 references that are not finalized

batch_processor:
  # INPUT FILES
  input_file: "decisions.txt"
  output_file: "decisions.txt"

  # REFERENCE SELECTION - Find unfinalized references
  selection_mode: "criteria"
  max_references: 5  # Limit to first 5 matches

  # Not used in criteria mode, but kept for reference
  reference_range:
    start: 1
    end: 999

  # Select references that are NOT finalized
  criteria:
    missing_primary_url: false     # Don't filter by primary URL
    missing_secondary_url: false   # Don't filter by secondary URL
    not_finalized: true            # ONLY select not finalized
    has_queries: false             # Don't filter by queries

  # QUERY GENERATION - Use simple mode for testing
  query_mode: "simple"  # 3 queries (faster, cheaper)

  # AUTO-FINALIZATION
  auto_finalize: true
  finalize_criteria:
    min_primary_score: 85
    min_secondary_score: 85
    require_title_match: true
    require_author_match: false
    max_warnings: 0

  # RATE LIMITING
  rate_limiting:
    delay_between_refs: 2000   # 2 seconds between refs
    delay_after_search: 1000   # 1 second after search
    max_retries: 3
    timeout: 30000

  # API ENDPOINTS
  api_base_url: "https://rrv521-1760738877.netlify.app/.netlify/functions"

  # LOGGING
  logging:
    verbose: true
    save_logs: true
    log_directory: "batch-logs"
    include_api_responses: false

  # RESUME CAPABILITY
  resume:
    enabled: true
    checkpoint_frequency: 1  # Save after every reference
