# Batch Processing Configuration - v16.6 Title Parsing Test
# Testing new cleanTitle() function with 25 references
# RIDs 600-624

batch_processor:
  # INPUT FILES
  input_file: "decisions.txt"
  output_file: "decisions.txt"

  # REFERENCE SELECTION
  selection_mode: "range"
  max_references: 25

  # Process refs 600-624 specifically
  reference_range:
    start: 600
    end: 624

  # QUERY GENERATION
  query_mode: "standard"  # 8 queries for better coverage

  # AUTO-FINALIZATION - Enabled for production
  auto_finalize: true

  finalize_criteria:
    min_primary_score: 75
    min_secondary_score: 70
    require_title_match: false
    require_author_match: false
    max_warnings: 2

  # RATE LIMITING
  rate_limiting:
    delay_between_refs: 300   # 300ms between operations
    delay_after_search: 500   # 500ms after search
    max_retries: 3
    timeout: 30000

  # API ENDPOINTS
  api_base_url: "https://rrv521-1760738877.netlify.app/.netlify/functions"

  # LOGGING
  logging:
    verbose: true
    save_logs: true
    log_directory: "batch-logs"
    include_api_responses: false

  # RESUME CAPABILITY
  resume:
    enabled: true
    checkpoint_frequency: 5  # Save every 5 references
