#!/usr/bin/env python3
"""
Update generateQueries() to use v18.0 Query Evolution strategies
"""

# Read the HTML file
with open('rr_v18.0.html', 'r') as f:
    html = f.read()

# Find and replace the simple mode section
# Old code starts with: // v14.3: Check if simple mode is enabled
# and ends before the else clause for standard 8-query mode

old_simple_mode = '''                    // v14.3: Check if simple mode is enabled
                    if (this.simpleQueries) {
                        totalQueries = 3;
                        // Detect work type for review query
                        const otherInfo = (ref.other || '').toLowerCase();
                        let workType = 'book';
                        if (otherInfo.includes('journal') || otherInfo.includes('article')) {
                            workType = 'article';
                        } else if (otherInfo.includes('film') || otherInfo.includes('documentary')) {
                            workType = 'film';
                        }

                        prompt = `You are helping find URLs for an academic reference. Generate EXACTLY 3 search queries using this simple structure:

REFERENCE:
Title: ${ref.title || 'Unknown'}
Authors: ${ref.authors || 'Unknown'}
Year: ${ref.year || 'Unknown'}
Other Info: ${ref.other || 'None'}

RELEVANCE (context for topic keywords):
${ref.relevance_text || 'No context provided'}

QUERY STRUCTURE (generate EXACTLY 3 queries):

Query 1 - BROAD TITLE+AUTHOR SEARCH:
Format: "{exact title}" {author last name}
Goal: Cast wide net for the work in any format
Example: "Making the Social World" Searle

Query 2 - REVIEW SEARCH:
Format: "{exact title}" ${workType} review
Goal: Find scholarly reviews or analyses of THIS SPECIFIC WORK
Example: "Making the Social World" book review

Query 3 - TOPIC KEYWORDS:
Format: {5-8 key concepts/topics from title and relevance, NO quotes}
Goal: Broader conceptual search for related discussions
Example: social ontology collective intentionality institutional facts Searle

IMPORTANT:
- Query 1: Use full exact title in quotes + author last name only
- Query 2: Use full exact title in quotes + "${workType} review"
- Query 3: Extract 5-8 core concepts/keywords, no quotes, space-separated
- Return ONLY 3 queries, one per line
- No labels, numbering, or explanations`;'''

new_simple_mode = '''                    // v18.0: Query Evolution mode (replaces v14.3 simple mode)
                    if (this.simpleQueries) {
                        totalQueries = 1;  // Single optimized query using strategy

                        // Select and generate query using v21.0 strategies
                        const evolutionQuery = this.generateQueryWithStrategy(ref);
                        const strategy = this.lastStrategyUsed;

                        prompt = `You are helping find URLs for an academic reference using the Query Evolution algorithm.

REFERENCE:
Title: ${ref.title || 'Unknown'}
Authors: ${ref.authors || 'Unknown'}
Year: ${ref.year || 'Unknown'}
Other Info: ${ref.other || 'None'}

RELEVANCE (context):
${ref.relevance_text || 'No context provided'}

SELECTED STRATEGY: ${strategy}
BASE QUERY: ${evolutionQuery}

YOUR TASK:
Using the base query "${evolutionQuery}" (generated by ${strategy} strategy), create a refined Google search query that will find:
1. The PRIMARY source (full text, official page, or purchase page)
2. SECONDARY sources (reviews, analyses, or discussions)

Return EXACTLY 1 optimized query that combines the base query with appropriate search operators.

OPTIMIZATION GUIDELINES:
- If title < 20 chars: Add author name or year
- If academic work: Consider adding "site:.edu OR PDF OR filetype:pdf"
- If book: Consider adding "Amazon OR publisher name"
- If journal article: Consider adding "DOI OR JSTOR OR PubMed"
- Keep query under 120 characters
- Use quotes for exact phrases only when helpful

Return ONLY the optimized query, no labels or explanations.`;'''

# Replace
html = html.replace(old_simple_mode, new_simple_mode)

# Write back
with open('rr_v18.0.html', 'w') as f:
    f.write(html)

print("✅ Successfully updated generateQueries() to use v18.0 strategies")
